### ISSUE TITLE
Allow customization of highlighted styles

### ISSUE THREAD

**Issue by octref** [GhostText/GhostText#156]
I'm wondering if you can add an option to allow users to configure the style of the highlighted text areas. I'd prefer a bright border rather than shadows bleeding in. Thanks!

**Comment by bfred-it** [comment]
I can't add an option for this, but you can use Stylush to override it, e.g.

```css
[style*="rgb(0,173,238) 0 0 20px 5px inset"] {
	box-shadow: none !important; /* reset shadow */
	/* your style */
}
```
