### ISSUE TITLE
Add autodeployment to Mozilla Addons

### ISSUE THREAD

**Issue by bfred-it** [GhostText/GhostText#93]
AMO deployer:
https://github.com/erikdesjardins/firefox-extension-deploy

Current autodeployment:
https://github.com/GhostText/GhostText/blob/78b289bde328c3f2f3cd7425f576f3263e0013b1/package.json#L12

The addon:
https://addons.mozilla.org/en-US/firefox/addon/ghosttext/

**Comment by bfred-it** [comment]
For reference, this is how we've done it for npmhub:

- [.travis.yml](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/.travis.yml#L6-L13)
    
    ```yml
    env:
      - EXTENSION_ID=kbbbjimdjbjclaebffknlabpogocablj
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run update-version; npm run release-cws; npm run release-amo
      on:
          branch: master
    ```

- [package.json](https://github.com/npmhub/npmhub/blob/0b3040a212027cc4fd4910a98ee0e478633480ef/package.json#L16-L18)

    ```json
    {
        "scripts": {
          "test": "xo && web-ext lint",
          "release-amo": "OK='Your add-on has been submitted for review.'; web-ext sign -s extension | sed -n \"s/\\($OK\\).*$/\\1/;1,/$OK/p\" | perl -pe 'BEGIN { $s=1 } END { exit $s } $s=0 if /'\"$OK\"'/;'",
          "release-cws": "webstore upload --source=extension --auto-publish",
          "update-version": "dot-json extension/manifest.json version $(date -u +%Y.%-m.%-d.%-H%M)"
        }
    }
    ```
